type recipesType = {
  name: string;
  description: string;
  snippet: string;
  time: number;
  ingredients: string[];
  categories: string[];
  image_url: string;
};

export const recipes: recipesType[] = [
  {
    name: "Creamy Garlic Shrimp Pasta",
    description:
      "Creamy garlic shrimp pasta combines tender shrimp with linguine in a rich sauce made from cream, garlic, Parmesan, and a touch of lemon. The shrimp cook quickly and develop a light golden color while the sauce becomes silky and coats the pasta. Fresh parsley adds brightness and makes this an easy but impressive dinner for busy evenings.",
    snippet:
      "Creamy linguine with garlic shrimp, Parmesan, lemon, and parsley.",
    time: 30,
    ingredients: [
      "300 g shrimp",
      "250 g linguine",
      "200 ml heavy cream",
      "50 g Parmesan",
      "4 cloves garlic",
      "1/2 lemon",
      "2 tbsp olive oil",
      "2 tbsp parsley",
      "1/2 tsp black pepper",
    ],
    categories: ["Dinner", "Fish", "Fast"],
    image_url: "https://loremflickr.com/800/600/shrimp,pasta,garlic?lock=401",
  },
  {
    name: "Classic Chicken Noodle Soup",
    description:
      "Classic chicken noodle soup is a comforting combination of tender chicken, vegetables, noodles, and a flavorful broth. Carrots, celery, and onions provide a savory base while herbs add warmth and freshness. The soup is simple enough for an ordinary weekday but also works beautifully as a cozy meal when the weather is cold.",
    snippet: "Comforting chicken soup with vegetables, noodles, and herbs.",
    time: 50,
    ingredients: [
      "400 g chicken breast",
      "150 g egg noodles",
      "2 carrots",
      "2 celery stalks",
      "1 onion",
      "1.5 L chicken broth",
      "2 cloves garlic",
      "2 tbsp parsley",
      "1 tsp thyme",
      "1/2 tsp black pepper",
    ],
    categories: ["Lunch", "Chicken"],
    image_url: "https://loremflickr.com/800/600/chicken,noodle,soup?lock=402",
  },
  {
    name: "Creamy Mushroom Tagliatelle",
    description:
      "Creamy mushroom tagliatelle is a rich vegetarian pasta dish featuring browned mushrooms, garlic, cream, Parmesan, and fresh herbs. Cooking the mushrooms until deeply golden gives the sauce a much stronger flavor than simply simmering them. The finished pasta is silky, savory, and comforting while remaining straightforward enough for a weeknight dinner.",
    snippet: "Tagliatelle with golden mushrooms in a creamy Parmesan sauce.",
    time: 30,
    ingredients: [
      "250 g tagliatelle",
      "300 g mushrooms",
      "200 ml heavy cream",
      "60 g Parmesan",
      "1 onion",
      "3 cloves garlic",
      "2 tbsp butter",
      "1 tbsp parsley",
      "1/2 tsp black pepper",
    ],
    categories: ["Dinner", "Vegetarian", "Fast"],
    image_url:
      "https://loremflickr.com/800/600/mushroom,tagliatelle,pasta?lock=403",
  },
  {
    name: "Spicy Chicken Ramen",
    description:
      "Spicy chicken ramen combines springy noodles with tender chicken, mushrooms, spinach, spring onions, and a rich spicy broth. Chili paste and garlic provide heat while soy sauce and sesame oil add savory depth. The recipe can be customized with a soft-boiled egg, additional vegetables, or extra chili depending on how spicy you like your ramen.",
    snippet: "Spicy ramen with chicken, mushrooms, spinach, and chili broth.",
    time: 35,
    ingredients: [
      "250 g chicken breast",
      "200 g ramen noodles",
      "1 L chicken broth",
      "150 g mushrooms",
      "100 g spinach",
      "2 spring onions",
      "2 cloves garlic",
      "1 tbsp chili paste",
      "2 tbsp soy sauce",
      "1 tsp sesame oil",
    ],
    categories: ["Dinner", "Chicken"],
    image_url: "https://loremflickr.com/800/600/chicken,ramen,spicy?lock=404",
  },
  {
    name: "Roasted Vegetable Couscous",
    description:
      "Roasted vegetable couscous is a colorful vegetarian meal made with fluffy couscous, roasted zucchini, peppers, carrots, and red onion. The vegetables become caramelized and slightly crispy in the oven, while lemon juice and fresh herbs keep the dish bright. It can be served warm as a main course or cold as a filling lunch salad.",
    snippet: "Fluffy couscous with caramelized roasted vegetables and herbs.",
    time: 45,
    ingredients: [
      "250 g couscous",
      "1 zucchini",
      "2 bell peppers",
      "2 carrots",
      "1 red onion",
      "500 ml vegetable broth",
      "3 tbsp olive oil",
      "1 lemon",
      "3 tbsp parsley",
      "1 tsp cumin",
    ],
    categories: ["Lunch", "Vegetarian"],
    image_url:
      "https://loremflickr.com/800/600/couscous,roasted,vegetables?lock=405",
  },
  {
    name: "Beef and Broccoli Stir-Fry",
    description:
      "Beef and broccoli stir-fry combines thinly sliced beef with crisp broccoli in a glossy soy-based sauce. Garlic, ginger, sesame oil, and a little brown sugar create a balanced mixture of savory, sweet, and aromatic flavors. The entire dish comes together quickly in a hot pan and is best served over steamed rice.",
    snippet: "Tender beef and broccoli in a savory ginger soy sauce.",
    time: 25,
    ingredients: [
      "350 g beef",
      "400 g broccoli",
      "2 cloves garlic",
      "2 cm ginger",
      "4 tbsp soy sauce",
      "1 tbsp brown sugar",
      "1 tsp sesame oil",
      "1 tbsp vegetable oil",
      "300 g cooked rice",
    ],
    categories: ["Dinner", "Beef", "Fast"],
    image_url: "https://loremflickr.com/800/600/beef,broccoli,stirfry?lock=406",
  },
  {
    name: "Tomato Basil Bruschetta",
    description:
      "Tomato basil bruschetta is a simple Italian appetizer made from toasted slices of crusty bread topped with ripe tomatoes, fresh basil, garlic, olive oil, and balsamic vinegar. The contrast between crisp bread and juicy tomatoes makes it refreshing and satisfying. It is particularly good when using ripe tomatoes and high-quality olive oil.",
    snippet: "Crispy toasted bread topped with tomatoes, basil, and olive oil.",
    time: 15,
    ingredients: [
      "1 baguette",
      "400 g tomatoes",
      "1 handful fresh basil",
      "2 cloves garlic",
      "3 tbsp olive oil",
      "1 tbsp balsamic vinegar",
      "1/2 tsp salt",
      "1/4 tsp black pepper",
    ],
    categories: ["Vegetarian", "Fast"],
    image_url:
      "https://loremflickr.com/800/600/bruschetta,tomato,basil?lock=407",
  },
  {
    name: "Creamy Beef Pasta",
    description:
      "Creamy beef pasta combines seasoned ground beef with pasta, onions, garlic, tomatoes, cream, and Parmesan. The beef develops a rich browned flavor while the cream creates a smooth sauce that coats every piece of pasta. It is a hearty meal that can be prepared quickly and works particularly well for feeding several people.",
    snippet: "Hearty pasta with seasoned beef in a creamy tomato sauce.",
    time: 35,
    ingredients: [
      "300 g ground beef",
      "250 g penne",
      "1 onion",
      "3 cloves garlic",
      "200 g crushed tomatoes",
      "150 ml heavy cream",
      "50 g Parmesan",
      "1 tsp oregano",
      "1 tbsp olive oil",
    ],
    categories: ["Dinner", "Beef"],
    image_url: "https://loremflickr.com/800/600/beef,pasta,creamy?lock=408",
  },
  {
    name: "Vegetarian Bean Chili",
    description:
      "Vegetarian bean chili is a hearty one-pot meal made with several types of beans, tomatoes, peppers, corn, onions, and warming spices. The chili becomes thick and flavorful as it simmers, while the combination of beans provides plenty of texture and substance. Serve it with rice, tortilla chips, avocado, or fresh herbs.",
    snippet:
      "Hearty meat-free chili with beans, vegetables, tomatoes, and spices.",
    time: 50,
    ingredients: [
      "400 g kidney beans",
      "400 g black beans",
      "400 g chopped tomatoes",
      "1 red bell pepper",
      "1 onion",
      "150 g corn",
      "2 cloves garlic",
      "2 tsp chili powder",
      "1 tsp cumin",
      "250 ml vegetable broth",
    ],
    categories: ["Dinner", "Vegetarian", "Vegan"],
    image_url: "https://loremflickr.com/800/600/vegetarian,bean,chili?lock=409",
  },
  {
    name: "Blueberry Oatmeal Bowl",
    description:
      "This blueberry oatmeal bowl is a warm and filling breakfast made with oats, milk, blueberries, banana, cinnamon, and a little honey. The oats become creamy while the fruit adds natural sweetness and freshness. Nuts or seeds can be added for extra texture, making this an easy breakfast that can be adjusted to suit different tastes.",
    snippet: "Warm creamy oats with blueberries, banana, cinnamon, and honey.",
    time: 10,
    ingredients: [
      "80 g rolled oats",
      "250 ml milk",
      "100 g blueberries",
      "1 banana",
      "1/2 tsp cinnamon",
      "1 tbsp honey",
      "20 g walnuts",
    ],
    categories: ["Breakfast", "Sweet", "Fast"],
    image_url:
      "https://loremflickr.com/800/600/blueberry,oatmeal,bowl?lock=410",
  },
  {
    name: "Lemon Herb Chicken Rice",
    description:
      "Lemon herb chicken rice is a simple one-pan style meal where seasoned chicken is cooked with rice, garlic, herbs, lemon, and chicken broth. The rice absorbs the flavorful juices from the chicken while the lemon adds brightness. It is filling, easy to portion, and requires relatively little cleanup compared with preparing separate side dishes.",
    snippet: "One-pan chicken and rice with lemon, garlic, and herbs.",
    time: 45,
    ingredients: [
      "400 g chicken thighs",
      "250 g long-grain rice",
      "600 ml chicken broth",
      "1 lemon",
      "4 cloves garlic",
      "1 onion",
      "2 tbsp olive oil",
      "1 tsp oregano",
      "1 tsp thyme",
    ],
    categories: ["Dinner", "Chicken"],
    image_url: "https://loremflickr.com/800/600/chicken,rice,lemon?lock=411",
  },
  {
    name: "Creamy Pumpkin Pasta",
    description:
      "Creamy pumpkin pasta is a cozy autumn-inspired dish that turns pumpkin puree into a silky sauce with cream, Parmesan, garlic, and sage. The pumpkin provides natural sweetness while Parmesan and herbs add savory depth. It is an easy vegetarian dinner that feels comforting without requiring a long list of complicated ingredients.",
    snippet: "Creamy pumpkin pasta with Parmesan, garlic, and sage.",
    time: 30,
    ingredients: [
      "250 g pasta",
      "300 g pumpkin puree",
      "150 ml heavy cream",
      "60 g Parmesan",
      "3 cloves garlic",
      "1 tbsp butter",
      "1 tsp dried sage",
      "1/2 tsp nutmeg",
      "1/2 tsp black pepper",
    ],
    categories: ["Dinner", "Vegetarian", "Fast"],
    image_url: "https://loremflickr.com/800/600/pumpkin,pasta,creamy?lock=412",
  },
  {
    name: "Crispy Chicken Wrap",
    description:
      "Crispy chicken wraps combine crunchy breaded chicken with lettuce, tomato, cucumber, cheese, and a creamy sauce inside a soft tortilla. The contrast between the crisp chicken and fresh vegetables makes the wrap satisfying without being overly heavy. It is particularly convenient for lunch because the ingredients can be prepared separately and assembled just before eating.",
    snippet: "Crunchy chicken wrap with fresh vegetables, cheese, and sauce.",
    time: 30,
    ingredients: [
      "300 g chicken breast",
      "4 flour tortillas",
      "80 g breadcrumbs",
      "1 egg",
      "100 g lettuce",
      "2 tomatoes",
      "1 cucumber",
      "80 g cheddar",
      "100 g mayonnaise",
    ],
    categories: ["Lunch", "Chicken", "Fast"],
    image_url: "https://loremflickr.com/800/600/crispy,chicken,wrap?lock=413",
  },
  {
    name: "Creamy Broccoli Pasta",
    description:
      "Creamy broccoli pasta is a quick vegetarian meal that combines tender broccoli with pasta, garlic, cream, and Parmesan. Some of the broccoli is blended into the sauce while the rest remains in small pieces, creating a creamy texture with plenty of vegetables. Lemon zest and black pepper help balance the richness of the finished dish.",
    snippet: "Creamy pasta with broccoli, garlic, Parmesan, and lemon.",
    time: 25,
    ingredients: [
      "250 g pasta",
      "350 g broccoli",
      "180 ml heavy cream",
      "50 g Parmesan",
      "3 cloves garlic",
      "1/2 lemon",
      "1 tbsp olive oil",
      "1/2 tsp black pepper",
    ],
    categories: ["Dinner", "Vegetarian", "Fast"],
    image_url: "https://loremflickr.com/800/600/broccoli,pasta,creamy?lock=414",
  },
  {
    name: "Teriyaki Beef Noodles",
    description:
      "Teriyaki beef noodles combine thinly sliced beef with noodles, bell peppers, carrots, spring onions, and a sweet and savory homemade teriyaki sauce. The beef is quickly seared over high heat before being tossed with the vegetables and noodles. Sesame seeds and spring onions provide a fresh finishing touch.",
    snippet: "Stir-fried beef noodles with vegetables and teriyaki sauce.",
    time: 30,
    ingredients: [
      "300 g beef",
      "250 g noodles",
      "1 bell pepper",
      "1 carrot",
      "3 spring onions",
      "4 tbsp soy sauce",
      "2 tbsp honey",
      "1 tbsp rice vinegar",
      "1 tsp sesame oil",
      "1 tbsp sesame seeds",
    ],
    categories: ["Dinner", "Beef", "Fast"],
    image_url: "https://loremflickr.com/800/600/beef,noodles,teriyaki?lock=415",
  },
  {
    name: "Spinach Feta Omelette",
    description:
      "Spinach feta omelette is a protein-rich breakfast made with fluffy eggs, fresh spinach, crumbled feta, and herbs. The spinach is quickly wilted before the eggs are added, while the feta melts slightly into the warm omelette and provides a salty contrast. It takes only a few minutes and works equally well for breakfast, lunch, or a light dinner.",
    snippet: "Fluffy omelette filled with spinach, feta, and fresh herbs.",
    time: 15,
    ingredients: [
      "3 eggs",
      "80 g spinach",
      "60 g feta",
      "1 tbsp butter",
      "1 spring onion",
      "1 tbsp parsley",
      "1/4 tsp black pepper",
    ],
    categories: ["Breakfast", "Vegetarian", "Salty", "Fast"],
    image_url: "https://loremflickr.com/800/600/spinach,feta,omelette?lock=416",
  },
  {
    name: "Roasted Tomato Bruschetta Pasta",
    description:
      "Roasted tomato bruschetta pasta combines sweet roasted tomatoes with pasta, garlic, basil, olive oil, and Parmesan. Roasting concentrates the tomatoes and gives them a deeper flavor before they are tossed with the freshly cooked pasta. The result is a bright vegetarian dish that feels light while still being satisfying enough for dinner.",
    snippet:
      "Pasta with roasted tomatoes, garlic, basil, olive oil, and Parmesan.",
    time: 40,
    ingredients: [
      "250 g spaghetti",
      "400 g cherry tomatoes",
      "3 cloves garlic",
      "1 handful fresh basil",
      "3 tbsp olive oil",
      "50 g Parmesan",
      "1 tbsp balsamic vinegar",
      "1/2 tsp black pepper",
    ],
    categories: ["Dinner", "Vegetarian"],
    image_url: "https://loremflickr.com/800/600/tomato,pasta,basil?lock=417",
  },
  {
    name: "Chicken and Vegetable Curry",
    description:
      "Chicken and vegetable curry combines tender chicken with carrots, bell peppers, peas, tomatoes, and aromatic spices in a rich sauce. Garlic, ginger, curry powder, and coconut milk create a fragrant base while the vegetables add color and texture. Serve it with steamed rice or naan for a satisfying meal with plenty of comforting flavor.",
    snippet: "Fragrant chicken curry with vegetables and creamy coconut sauce.",
    time: 45,
    ingredients: [
      "400 g chicken breast",
      "1 carrot",
      "1 bell pepper",
      "150 g peas",
      "1 onion",
      "3 cloves garlic",
      "2 cm ginger",
      "2 tbsp curry powder",
      "400 ml coconut milk",
      "200 g chopped tomatoes",
    ],
    categories: ["Dinner", "Chicken"],
    image_url:
      "https://loremflickr.com/800/600/chicken,vegetable,curry?lock=418",
  },
  {
    name: "Mediterranean Baked Feta",
    description:
      "Mediterranean baked feta is a simple oven dish featuring a block of feta surrounded by tomatoes, peppers, olives, garlic, and herbs. As the vegetables roast, their juices combine with the melted feta and olive oil to create a flavorful mixture that works beautifully with crusty bread. It can be served as a light meal or shared appetizer.",
    snippet: "Baked feta with roasted tomatoes, peppers, olives, and herbs.",
    time: 35,
    ingredients: [
      "200 g feta",
      "300 g cherry tomatoes",
      "1 bell pepper",
      "80 g olives",
      "3 cloves garlic",
      "3 tbsp olive oil",
      "1 tsp oregano",
      "1/2 tsp chili flakes",
    ],
    categories: ["Lunch", "Vegetarian", "Salty"],
    image_url:
      "https://loremflickr.com/800/600/baked,feta,tomato,olives?lock=419",
  },
  {
    name: "Beef Stuffed Bell Peppers",
    description:
      "Beef stuffed bell peppers are filled with seasoned ground beef, rice, tomatoes, onions, garlic, and herbs before being baked until the peppers become tender. Melted cheese on top adds a rich finishing layer. The peppers make the meal easy to portion and provide vegetables and protein in one colorful and satisfying dish.",
    snippet:
      "Bell peppers stuffed with seasoned beef, rice, tomato, and cheese.",
    time: 60,
    ingredients: [
      "4 bell peppers",
      "400 g ground beef",
      "200 g cooked rice",
      "200 g chopped tomatoes",
      "1 onion",
      "2 cloves garlic",
      "100 g mozzarella",
      "1 tsp oregano",
      "1 tbsp olive oil",
    ],
    categories: ["Dinner", "Beef", "Takes Time"],
    image_url:
      "https://loremflickr.com/800/600/stuffed,bell,peppers,beef?lock=420",
  },
  {
    name: "Cinnamon Sugar Donuts",
    description:
      "These cinnamon sugar donuts are soft, lightly sweet, and coated in a fragrant mixture of cinnamon and sugar. The dough is prepared with milk, butter, eggs, and yeast before being shaped and baked or fried until golden. They are especially enjoyable while still warm and make a fun weekend breakfast or homemade dessert.",
    snippet: "Soft homemade donuts coated with cinnamon sugar.",
    time: 70,
    ingredients: [
      "400 g flour",
      "200 ml milk",
      "50 g butter",
      "50 g sugar",
      "1 egg",
      "7 g dry yeast",
      "1 tsp vanilla",
      "80 g sugar",
      "2 tsp cinnamon",
    ],
    categories: ["Breakfast", "Dessert", "Sweet", "Takes Time"],
    image_url: "https://loremflickr.com/800/600/cinnamon,sugar,donuts?lock=421",
  },
  {
    name: "Creamy Potato Leek Soup",
    description:
      "Creamy potato leek soup is a smooth and comforting soup made with potatoes, leeks, onion, garlic, vegetable broth, and cream. The leeks provide a gentle sweetness while the potatoes give the soup a naturally thick and creamy consistency. Fresh herbs and black pepper add brightness to this simple meal that is especially good on colder days.",
    snippet: "Smooth creamy soup with potatoes, leeks, garlic, and herbs.",
    time: 45,
    ingredients: [
      "600 g potatoes",
      "3 leeks",
      "1 onion",
      "2 cloves garlic",
      "1 L vegetable broth",
      "150 ml heavy cream",
      "2 tbsp butter",
      "1 tsp thyme",
      "1/2 tsp black pepper",
    ],
    categories: ["Lunch", "Vegetarian"],
    image_url: "https://loremflickr.com/800/600/potato,leek,soup?lock=422",
  },
  {
    name: "Tuna Pasta Salad",
    description:
      "Tuna pasta salad combines cooked pasta with tuna, sweet corn, cucumber, tomatoes, red onion, and a creamy lemon dressing. It is refreshing enough for warm days while still providing a filling combination of carbohydrates and protein. The salad can be prepared in advance and served chilled, making it convenient for packed lunches or casual gatherings.",
    snippet:
      "Cold pasta salad with tuna, vegetables, corn, and lemon dressing.",
    time: 20,
    ingredients: [
      "250 g pasta",
      "2 cans tuna",
      "150 g corn",
      "1 cucumber",
      "200 g cherry tomatoes",
      "1/2 red onion",
      "100 g mayonnaise",
      "2 tbsp lemon juice",
      "1 tsp mustard",
    ],
    categories: ["Lunch", "Fish", "Fast"],
    image_url: "https://loremflickr.com/800/600/tuna,pasta,salad?lock=423",
  },
  {
    name: "Vegan Lentil Bolognese",
    description:
      "Vegan lentil Bolognese replaces ground meat with hearty lentils while keeping the rich tomato-based character of a traditional pasta sauce. Onions, carrots, celery, garlic, tomatoes, and Italian herbs create a flavorful base, while lentils add texture and substance. Serve it over spaghetti for a filling plant-based dinner that reheats very well.",
    snippet: "Rich tomato Bolognese made with lentils instead of meat.",
    time: 55,
    ingredients: [
      "200 g dry lentils",
      "400 g spaghetti",
      "1 onion",
      "2 carrots",
      "2 celery stalks",
      "3 cloves garlic",
      "800 g chopped tomatoes",
      "500 ml vegetable broth",
      "2 tsp oregano",
      "2 tbsp olive oil",
    ],
    categories: ["Dinner", "Vegan", "Takes Time"],
    image_url:
      "https://loremflickr.com/800/600/lentil,bolognese,pasta?lock=424",
  },
  {
    name: "Cheesy Potato Casserole",
    description:
      "Cheesy potato casserole layers thinly sliced potatoes with cream, garlic, onions, and plenty of melted cheese. The potatoes slowly become tender in the oven while the top develops a golden crust. It is rich and comforting enough to serve as a main vegetarian meal with a salad, or as a substantial side dish alongside roasted meat.",
    snippet: "Creamy baked potatoes layered with garlic, cream, and cheese.",
    time: 75,
    ingredients: [
      "1 kg potatoes",
      "250 ml heavy cream",
      "150 ml milk",
      "200 g grated cheese",
      "1 onion",
      "3 cloves garlic",
      "30 g butter",
      "1/2 tsp nutmeg",
      "1/2 tsp black pepper",
    ],
    categories: ["Dinner", "Vegetarian", "Takes Time"],
    image_url:
      "https://loremflickr.com/800/600/potato,casserole,cheese?lock=425",
  },
  {
    name: "Honey Garlic Salmon Bowl",
    description:
      "Honey garlic salmon bowls combine flaky salmon with rice, roasted broccoli, carrots, and a glossy honey garlic sauce. The salmon develops a caramelized coating while remaining tender inside, and the vegetables provide freshness and crunch. The bowl is easy to customize with avocado, cucumber, sesame seeds, or additional chili.",
    snippet: "Salmon rice bowl with honey garlic glaze and roasted vegetables.",
    time: 35,
    ingredients: [
      "350 g salmon",
      "300 g cooked rice",
      "250 g broccoli",
      "2 carrots",
      "3 cloves garlic",
      "2 tbsp honey",
      "3 tbsp soy sauce",
      "1 tsp sesame oil",
      "1 tbsp sesame seeds",
    ],
    categories: ["Dinner", "Fish"],
    image_url: "https://loremflickr.com/800/600/salmon,rice,bowl?lock=426",
  },
  {
    name: "Strawberry Yogurt Parfait",
    description:
      "Strawberry yogurt parfait is a simple layered dessert or breakfast made with creamy yogurt, fresh strawberries, crunchy granola, and a little honey. The combination of cool yogurt, juicy fruit, and crisp granola creates plenty of texture. It takes only a few minutes to assemble and can easily be prepared in individual glasses for serving.",
    snippet: "Layered yogurt with strawberries, granola, and honey.",
    time: 10,
    ingredients: [
      "400 g Greek yogurt",
      "250 g strawberries",
      "100 g granola",
      "2 tbsp honey",
      "1 tsp vanilla extract",
    ],
    categories: ["Breakfast", "Dessert", "Sweet", "Fast"],
    image_url:
      "https://loremflickr.com/800/600/strawberry,yogurt,parfait?lock=427",
  },
  {
    name: "Moroccan Chickpea Tagine",
    description:
      "Moroccan chickpea tagine is a fragrant plant-based stew made with chickpeas, tomatoes, carrots, zucchini, dried apricots, and warming spices. Cumin, cinnamon, coriander, and paprika create a deep aromatic flavor while the vegetables slowly soften in the sauce. Serve it with couscous or flatbread to absorb the flavorful cooking liquid.",
    snippet: "Fragrant chickpea and vegetable stew with Moroccan spices.",
    time: 65,
    ingredients: [
      "400 g chickpeas",
      "2 carrots",
      "1 zucchini",
      "400 g chopped tomatoes",
      "100 g dried apricots",
      "1 onion",
      "3 cloves garlic",
      "1 tsp cumin",
      "1 tsp paprika",
      "1/2 tsp cinnamon",
      "300 ml vegetable broth",
    ],
    categories: ["Dinner", "Vegan", "Takes Time"],
    image_url:
      "https://loremflickr.com/800/600/moroccan,chickpea,tagine?lock=428",
  },
  {
    name: "Baked Chicken Drumsticks",
    description:
      "Baked chicken drumsticks are seasoned with paprika, garlic, herbs, olive oil, and black pepper before being roasted until the skin becomes golden and crisp. The meat stays juicy underneath the flavorful coating. They are inexpensive, easy to prepare in larger quantities, and pair well with roasted potatoes, rice, coleslaw, or steamed vegetables.",
    snippet: "Crispy oven-baked chicken drumsticks with garlic and paprika.",
    time: 60,
    ingredients: [
      "1 kg chicken drumsticks",
      "3 tbsp olive oil",
      "2 tsp paprika",
      "4 cloves garlic",
      "1 tsp thyme",
      "1 tsp oregano",
      "1 tsp salt",
      "1/2 tsp black pepper",
    ],
    categories: ["Dinner", "Chicken", "Takes Time"],
    image_url:
      "https://loremflickr.com/800/600/baked,chicken,drumsticks?lock=429",
  },
  {
    name: "Chocolate Banana Muffins",
    description:
      "Chocolate banana muffins are soft, moist muffins made with ripe bananas, cocoa powder, chocolate chips, and vanilla. The bananas provide natural sweetness and moisture while the cocoa creates a rich chocolate flavor. They are easy to prepare in one bowl and make a convenient breakfast, snack, or dessert that can be stored for several days.",
    snippet: "Soft banana muffins packed with cocoa and chocolate chips.",
    time: 35,
    ingredients: [
      "3 ripe bananas",
      "200 g flour",
      "40 g cocoa powder",
      "100 g sugar",
      "2 eggs",
      "80 ml vegetable oil",
      "100 g chocolate chips",
      "1 tsp baking powder",
      "1 tsp vanilla extract",
    ],
    categories: ["Breakfast", "Dessert", "Sweet", "Fast"],
    image_url:
      "https://loremflickr.com/800/600/chocolate,banana,muffins?lock=430",
  },
];
