import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

import Link from "next/link";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="flex min-h-full flex-col">
        <nav className="flex gap-3">
          <Link href="/">HOME</Link>
          <Link href="/all-recipes">All Recipes</Link>
          <Link href="/create-recipe">CREATE RECIPE</Link>
          <Link href="/favorites">FAVORITES</Link>
        </nav>
        <main>{children}</main>
      </body>
    </html>
  );
}
